spring:
  application:
    name: product  # Replace with your application name
  rabbitmq:
    host: localhost  # Assuming the RabbitMQ service is named "rabbitmq" in Docker Compose
    port: 5672
    username: guest
    password: guest
  cloud:
    azure:
      cosmos:
        endpoint: https://localhost:8081
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: product
        populate-query-metrics: true

rabbitmq:
  queue:
    name: product
    exchange: product
    routing-key: product